kind: Pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: charliekenney23/docker-terraform-tflint
    autotag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
